### ISSUE TITLE
specifying alternative SSH port

### ISSUE THREAD

**Issue by Saffarofski** [omidmousavi/CSharp-SSH-VPN#1]
Please add a section to specify a port other than the default (22).

**Comment by mohsen-tahmasebi** [comment]
it does have the option to change the port in the source code but the download link is not updated yet @omidmousavi 
![image_2024-02-08_172208390](https://github.com/omidmousavi/CSharp-SSH-VPN/assets/75989704/c21875fc-edb0-428e-a9d3-9fbcb7869e39)

**Comment by omidmousavi** [comment]
This feature has already been added
Download the app again...
